---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - secret.fearning
  resources:
  - secretwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.fearning
  resources:
  - secretwatchers/finalizers
  verbs:
  - update
- apiGroups:
  - secret.fearning
  resources:
  - secretwatchers/status
  verbs:
  - get
  - patch
  - update
