# permissions for end users to view secretwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secretwatcher-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: secret-operator
    app.kubernetes.io/part-of: secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretwatcher-viewer-role
rules:
- apiGroups:
  - secret.fearning
  resources:
  - secretwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secret.fearning
  resources:
  - secretwatchers/status
  verbs:
  - get
